# -*- coding: utf-8 -*-
"""newspaper-articles-text-to-speech.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d1bnvjpXkq5hRZVhcwLudEF_KYLnVie7
"""

pip install newspaper3k

pip install package_name

pip install --user -U nltk

pip install gTTS

#Import the libraries
from newspaper import Article
import nltk
from gtts import gTTS
import os

#Get the article
article = Article('https://webrazzi.com/2023/02/13/ibb-den-binalarin-risk-durumunun-tespiti-icin-inceleme-talep-platformu-bina-tespiti')

article.download()
article.parse()

nltk.download('punkt')
article.nlp()

#Get the articles text
mytext = article.text

language = 'tr'

myobj = gTTS(text=mytext, lang=language, slow=False)

myobj.save("read_article.mp3")

